### ISSUE TITLE
error received

### ISSUE THREAD

**Issue by vperezma** [coreyshuman/GeekwiseApplicationSecurity#1]
https://forums.docker.com/t/getting-panic-spanic-standard-init-linux-go-178-exec-user-process-caused-no-such-file-or-directory-red-while-running-the-docker-image/27318/10

**Comment by coreyshuman** [comment]
Git on windows was converting line endings to `CRLF` which broke unix trying to execute the script.
Adding a rule to `.gitattributes` to enforce `LF` ending for all `.sh` files in the workspace has fixed this.
